### ISSUE TITLE
new design suggestions

### ISSUE THREAD

**Issue by scorcism** [asPerRequirements/oneliner#3]
new ui suggestions

**Comment by Sky-De** [comment]
Hi there
I would like to work on this, @scorcism please assign this to me

**Comment by scorcism** [comment]
go for it @Sky-De

**Comment by Sky-De** [comment]
@scorcism hi there , you have merged new commit, now please mark this as solved, thanks

**Comment by scorcism** [comment]
@Sky-De ohh I just
